before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
- main: ./cmd/kmgm/main.go

  env:
  - CGO_ENABLED=0

  goarch:
  - amd64

  goos:
  - linux

  ldflags:
  - -s -w
  - -X github.com/IPA-CyberLab/kmgm/version.Version={{.Version}}
  - -X github.com/IPA-CyberLab/kmgm/version.Commit={{.Commit}}
  # - -X main.date={{.Date}} -X main.builtBy=goreleaser

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
