// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pb/kmgm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationType int32

const (
	AuthenticationType_UNSPECIFIED     AuthenticationType = 0
	AuthenticationType_ANONYMOUS       AuthenticationType = 1
	AuthenticationType_BOOTSTRAP_TOKEN AuthenticationType = 2
	AuthenticationType_CLIENT_CERT     AuthenticationType = 3
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ANONYMOUS",
		2: "BOOTSTRAP_TOKEN",
		3: "CLIENT_CERT",
	}
	AuthenticationType_value = map[string]int32{
		"UNSPECIFIED":     0,
		"ANONYMOUS":       1,
		"BOOTSTRAP_TOKEN": 2,
		"CLIENT_CERT":     3,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_kmgm_proto_enumTypes[0].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_pb_kmgm_proto_enumTypes[0]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{0}
}

// Keep this in sync with wcrypto.KeyType
type KeyType int32

const (
	KeyType_KEYTYPE_UNSPECIFIED KeyType = 0
	KeyType_KEYTYPE_RSA4096     KeyType = 1
	KeyType_KEYTYPE_SECP256R1   KeyType = 2
	KeyType_KEYTYPE_RSA2048     KeyType = 3
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEYTYPE_UNSPECIFIED",
		1: "KEYTYPE_RSA4096",
		2: "KEYTYPE_SECP256R1",
		3: "KEYTYPE_RSA2048",
	}
	KeyType_value = map[string]int32{
		"KEYTYPE_UNSPECIFIED": 0,
		"KEYTYPE_RSA4096":     1,
		"KEYTYPE_SECP256R1":   2,
		"KEYTYPE_RSA2048":     3,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_kmgm_proto_enumTypes[1].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_pb_kmgm_proto_enumTypes[1]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{1}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pb_kmgm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{0}
}

type HelloResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion         int32                  `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	AuthenticationType AuthenticationType     `protobuf:"varint,2,opt,name=authentication_type,json=authenticationType,proto3,enum=kmgm.AuthenticationType" json:"authentication_type,omitempty"`
	AuthenticatedUser  string                 `protobuf:"bytes,3,opt,name=authenticated_user,json=authenticatedUser,proto3" json:"authenticated_user,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_pb_kmgm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *HelloResponse) GetAuthenticationType() AuthenticationType {
	if x != nil {
		return x.AuthenticationType
	}
	return AuthenticationType_UNSPECIFIED
}

func (x *HelloResponse) GetAuthenticatedUser() string {
	if x != nil {
		return x.AuthenticatedUser
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_pb_kmgm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{2}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_pb_kmgm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type DistinguishedName struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CommonName         string                 `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Organization       string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	OrganizationalUnit string                 `protobuf:"bytes,3,opt,name=organizational_unit,json=organizationalUnit,proto3" json:"organizational_unit,omitempty"`
	Country            string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Locality           string                 `protobuf:"bytes,5,opt,name=locality,proto3" json:"locality,omitempty"`
	Province           string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	StreetAddress      string                 `protobuf:"bytes,7,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	PostalCode         string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DistinguishedName) Reset() {
	*x = DistinguishedName{}
	mi := &file_pb_kmgm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistinguishedName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistinguishedName) ProtoMessage() {}

func (x *DistinguishedName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistinguishedName.ProtoReflect.Descriptor instead.
func (*DistinguishedName) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{4}
}

func (x *DistinguishedName) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *DistinguishedName) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *DistinguishedName) GetOrganizationalUnit() string {
	if x != nil {
		return x.OrganizationalUnit
	}
	return ""
}

func (x *DistinguishedName) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *DistinguishedName) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *DistinguishedName) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *DistinguishedName) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *DistinguishedName) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type Names struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dnsnames      []string               `protobuf:"bytes,1,rep,name=dnsnames,proto3" json:"dnsnames,omitempty"`
	Ipaddrs       []string               `protobuf:"bytes,2,rep,name=ipaddrs,proto3" json:"ipaddrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Names) Reset() {
	*x = Names{}
	mi := &file_pb_kmgm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Names) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Names) ProtoMessage() {}

func (x *Names) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Names.ProtoReflect.Descriptor instead.
func (*Names) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{5}
}

func (x *Names) GetDnsnames() []string {
	if x != nil {
		return x.Dnsnames
	}
	return nil
}

func (x *Names) GetIpaddrs() []string {
	if x != nil {
		return x.Ipaddrs
	}
	return nil
}

type KeyUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyUsage      uint32                 `protobuf:"varint,1,opt,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`
	ExtKeyUsages  []uint32               `protobuf:"varint,2,rep,packed,name=ext_key_usages,json=extKeyUsages,proto3" json:"ext_key_usages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyUsage) Reset() {
	*x = KeyUsage{}
	mi := &file_pb_kmgm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyUsage) ProtoMessage() {}

func (x *KeyUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyUsage.ProtoReflect.Descriptor instead.
func (*KeyUsage) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{6}
}

func (x *KeyUsage) GetKeyUsage() uint32 {
	if x != nil {
		return x.KeyUsage
	}
	return 0
}

func (x *KeyUsage) GetExtKeyUsages() []uint32 {
	if x != nil {
		return x.ExtKeyUsages
	}
	return nil
}

type SetupCARequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Profile          string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Subject          *DistinguishedName     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	KeyType          KeyType                `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=kmgm.KeyType" json:"key_type,omitempty"`
	NotAfterUnixtime int64                  `protobuf:"varint,4,opt,name=not_after_unixtime,json=notAfterUnixtime,proto3" json:"not_after_unixtime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetupCARequest) Reset() {
	*x = SetupCARequest{}
	mi := &file_pb_kmgm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCARequest) ProtoMessage() {}

func (x *SetupCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCARequest.ProtoReflect.Descriptor instead.
func (*SetupCARequest) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{7}
}

func (x *SetupCARequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SetupCARequest) GetSubject() *DistinguishedName {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *SetupCARequest) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_KEYTYPE_UNSPECIFIED
}

func (x *SetupCARequest) GetNotAfterUnixtime() int64 {
	if x != nil {
		return x.NotAfterUnixtime
	}
	return 0
}

type SetupCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupCAResponse) Reset() {
	*x = SetupCAResponse{}
	mi := &file_pb_kmgm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCAResponse) ProtoMessage() {}

func (x *SetupCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCAResponse.ProtoReflect.Descriptor instead.
func (*SetupCAResponse) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{8}
}

type IssuePreflightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePreflightRequest) Reset() {
	*x = IssuePreflightRequest{}
	mi := &file_pb_kmgm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePreflightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePreflightRequest) ProtoMessage() {}

func (x *IssuePreflightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePreflightRequest.ProtoReflect.Descriptor instead.
func (*IssuePreflightRequest) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{9}
}

func (x *IssuePreflightRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type IssuePreflightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePreflightResponse) Reset() {
	*x = IssuePreflightResponse{}
	mi := &file_pb_kmgm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePreflightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePreflightResponse) ProtoMessage() {}

func (x *IssuePreflightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePreflightResponse.ProtoReflect.Descriptor instead.
func (*IssuePreflightResponse) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{10}
}

type IssueCertificateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PublicKey        []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Subject          *DistinguishedName     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Names            *Names                 `protobuf:"bytes,3,opt,name=names,proto3" json:"names,omitempty"`
	NotAfterUnixtime int64                  `protobuf:"varint,4,opt,name=not_after_unixtime,json=notAfterUnixtime,proto3" json:"not_after_unixtime,omitempty"`
	KeyUsage         *KeyUsage              `protobuf:"bytes,5,opt,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`
	Profile          string                 `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IssueCertificateRequest) Reset() {
	*x = IssueCertificateRequest{}
	mi := &file_pb_kmgm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateRequest) ProtoMessage() {}

func (x *IssueCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateRequest.ProtoReflect.Descriptor instead.
func (*IssueCertificateRequest) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{11}
}

func (x *IssueCertificateRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *IssueCertificateRequest) GetSubject() *DistinguishedName {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *IssueCertificateRequest) GetNames() *Names {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *IssueCertificateRequest) GetNotAfterUnixtime() int64 {
	if x != nil {
		return x.NotAfterUnixtime
	}
	return 0
}

func (x *IssueCertificateRequest) GetKeyUsage() *KeyUsage {
	if x != nil {
		return x.KeyUsage
	}
	return nil
}

func (x *IssueCertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type IssueCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCertificateResponse) Reset() {
	*x = IssueCertificateResponse{}
	mi := &file_pb_kmgm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCertificateResponse) ProtoMessage() {}

func (x *IssueCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCertificateResponse.ProtoReflect.Descriptor instead.
func (*IssueCertificateResponse) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{12}
}

func (x *IssueCertificateResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	SerialNumber  int64                  `protobuf:"varint,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_pb_kmgm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{13}
}

func (x *GetCertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *GetCertificateRequest) GetSerialNumber() int64 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

type GetCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	mi := &file_pb_kmgm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kmgm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_pb_kmgm_proto_rawDescGZIP(), []int{14}
}

func (x *GetCertificateResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

var File_pb_kmgm_proto protoreflect.FileDescriptor

const file_pb_kmgm_proto_rawDesc = "" +
	"\n" +
	"\rpb/kmgm.proto\x12\x04kmgm\"\x0e\n" +
	"\fHelloRequest\"\xaa\x01\n" +
	"\rHelloResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\x05R\n" +
	"apiVersion\x12I\n" +
	"\x13authentication_type\x18\x02 \x01(\x0e2\x18.kmgm.AuthenticationTypeR\x12authenticationType\x12-\n" +
	"\x12authenticated_user\x18\x03 \x01(\tR\x11authenticatedUser\"\x13\n" +
	"\x11GetVersionRequest\"F\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\"\xa3\x02\n" +
	"\x11DistinguishedName\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12/\n" +
	"\x13organizational_unit\x18\x03 \x01(\tR\x12organizationalUnit\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1a\n" +
	"\blocality\x18\x05 \x01(\tR\blocality\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12%\n" +
	"\x0estreet_address\x18\a \x01(\tR\rstreetAddress\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\"=\n" +
	"\x05Names\x12\x1a\n" +
	"\bdnsnames\x18\x01 \x03(\tR\bdnsnames\x12\x18\n" +
	"\aipaddrs\x18\x02 \x03(\tR\aipaddrs\"M\n" +
	"\bKeyUsage\x12\x1b\n" +
	"\tkey_usage\x18\x01 \x01(\rR\bkeyUsage\x12$\n" +
	"\x0eext_key_usages\x18\x02 \x03(\rR\fextKeyUsages\"\xb5\x01\n" +
	"\x0eSetupCARequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x121\n" +
	"\asubject\x18\x02 \x01(\v2\x17.kmgm.DistinguishedNameR\asubject\x12(\n" +
	"\bkey_type\x18\x03 \x01(\x0e2\r.kmgm.KeyTypeR\akeyType\x12,\n" +
	"\x12not_after_unixtime\x18\x04 \x01(\x03R\x10notAfterUnixtime\"\x11\n" +
	"\x0fSetupCAResponse\"1\n" +
	"\x15IssuePreflightRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\"\x18\n" +
	"\x16IssuePreflightResponse\"\x83\x02\n" +
	"\x17IssueCertificateRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x121\n" +
	"\asubject\x18\x02 \x01(\v2\x17.kmgm.DistinguishedNameR\asubject\x12!\n" +
	"\x05names\x18\x03 \x01(\v2\v.kmgm.NamesR\x05names\x12,\n" +
	"\x12not_after_unixtime\x18\x04 \x01(\x03R\x10notAfterUnixtime\x12+\n" +
	"\tkey_usage\x18\x05 \x01(\v2\x0e.kmgm.KeyUsageR\bkeyUsage\x12\x18\n" +
	"\aprofile\x18\x06 \x01(\tR\aprofile\"<\n" +
	"\x18IssueCertificateResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\"V\n" +
	"\x15GetCertificateRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12#\n" +
	"\rserial_number\x18\x02 \x01(\x03R\fserialNumber\":\n" +
	"\x16GetCertificateResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate*Z\n" +
	"\x12AuthenticationType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\r\n" +
	"\tANONYMOUS\x10\x01\x12\x13\n" +
	"\x0fBOOTSTRAP_TOKEN\x10\x02\x12\x0f\n" +
	"\vCLIENT_CERT\x10\x03*c\n" +
	"\aKeyType\x12\x17\n" +
	"\x13KEYTYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fKEYTYPE_RSA4096\x10\x01\x12\x15\n" +
	"\x11KEYTYPE_SECP256R1\x10\x02\x12\x13\n" +
	"\x0fKEYTYPE_RSA2048\x10\x032@\n" +
	"\fHelloService\x120\n" +
	"\x05Hello\x12\x12.kmgm.HelloRequest\x1a\x13.kmgm.HelloResponse2Q\n" +
	"\x0eVersionService\x12?\n" +
	"\n" +
	"GetVersion\x12\x17.kmgm.GetVersionRequest\x1a\x18.kmgm.GetVersionResponse2\xb9\x02\n" +
	"\x12CertificateService\x126\n" +
	"\aSetupCA\x12\x14.kmgm.SetupCARequest\x1a\x15.kmgm.SetupCAResponse\x12K\n" +
	"\x0eIssuePreflight\x12\x1b.kmgm.IssuePreflightRequest\x1a\x1c.kmgm.IssuePreflightResponse\x12Q\n" +
	"\x10IssueCertificate\x12\x1d.kmgm.IssueCertificateRequest\x1a\x1e.kmgm.IssueCertificateResponse\x12K\n" +
	"\x0eGetCertificate\x12\x1b.kmgm.GetCertificateRequest\x1a\x1c.kmgm.GetCertificateResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_pb_kmgm_proto_rawDescOnce sync.Once
	file_pb_kmgm_proto_rawDescData []byte
)

func file_pb_kmgm_proto_rawDescGZIP() []byte {
	file_pb_kmgm_proto_rawDescOnce.Do(func() {
		file_pb_kmgm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_kmgm_proto_rawDesc), len(file_pb_kmgm_proto_rawDesc)))
	})
	return file_pb_kmgm_proto_rawDescData
}

var file_pb_kmgm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_kmgm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_kmgm_proto_goTypes = []any{
	(AuthenticationType)(0),          // 0: kmgm.AuthenticationType
	(KeyType)(0),                     // 1: kmgm.KeyType
	(*HelloRequest)(nil),             // 2: kmgm.HelloRequest
	(*HelloResponse)(nil),            // 3: kmgm.HelloResponse
	(*GetVersionRequest)(nil),        // 4: kmgm.GetVersionRequest
	(*GetVersionResponse)(nil),       // 5: kmgm.GetVersionResponse
	(*DistinguishedName)(nil),        // 6: kmgm.DistinguishedName
	(*Names)(nil),                    // 7: kmgm.Names
	(*KeyUsage)(nil),                 // 8: kmgm.KeyUsage
	(*SetupCARequest)(nil),           // 9: kmgm.SetupCARequest
	(*SetupCAResponse)(nil),          // 10: kmgm.SetupCAResponse
	(*IssuePreflightRequest)(nil),    // 11: kmgm.IssuePreflightRequest
	(*IssuePreflightResponse)(nil),   // 12: kmgm.IssuePreflightResponse
	(*IssueCertificateRequest)(nil),  // 13: kmgm.IssueCertificateRequest
	(*IssueCertificateResponse)(nil), // 14: kmgm.IssueCertificateResponse
	(*GetCertificateRequest)(nil),    // 15: kmgm.GetCertificateRequest
	(*GetCertificateResponse)(nil),   // 16: kmgm.GetCertificateResponse
}
var file_pb_kmgm_proto_depIdxs = []int32{
	0,  // 0: kmgm.HelloResponse.authentication_type:type_name -> kmgm.AuthenticationType
	6,  // 1: kmgm.SetupCARequest.subject:type_name -> kmgm.DistinguishedName
	1,  // 2: kmgm.SetupCARequest.key_type:type_name -> kmgm.KeyType
	6,  // 3: kmgm.IssueCertificateRequest.subject:type_name -> kmgm.DistinguishedName
	7,  // 4: kmgm.IssueCertificateRequest.names:type_name -> kmgm.Names
	8,  // 5: kmgm.IssueCertificateRequest.key_usage:type_name -> kmgm.KeyUsage
	2,  // 6: kmgm.HelloService.Hello:input_type -> kmgm.HelloRequest
	4,  // 7: kmgm.VersionService.GetVersion:input_type -> kmgm.GetVersionRequest
	9,  // 8: kmgm.CertificateService.SetupCA:input_type -> kmgm.SetupCARequest
	11, // 9: kmgm.CertificateService.IssuePreflight:input_type -> kmgm.IssuePreflightRequest
	13, // 10: kmgm.CertificateService.IssueCertificate:input_type -> kmgm.IssueCertificateRequest
	15, // 11: kmgm.CertificateService.GetCertificate:input_type -> kmgm.GetCertificateRequest
	3,  // 12: kmgm.HelloService.Hello:output_type -> kmgm.HelloResponse
	5,  // 13: kmgm.VersionService.GetVersion:output_type -> kmgm.GetVersionResponse
	10, // 14: kmgm.CertificateService.SetupCA:output_type -> kmgm.SetupCAResponse
	12, // 15: kmgm.CertificateService.IssuePreflight:output_type -> kmgm.IssuePreflightResponse
	14, // 16: kmgm.CertificateService.IssueCertificate:output_type -> kmgm.IssueCertificateResponse
	16, // 17: kmgm.CertificateService.GetCertificate:output_type -> kmgm.GetCertificateResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pb_kmgm_proto_init() }
func file_pb_kmgm_proto_init() {
	if File_pb_kmgm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_kmgm_proto_rawDesc), len(file_pb_kmgm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pb_kmgm_proto_goTypes,
		DependencyIndexes: file_pb_kmgm_proto_depIdxs,
		EnumInfos:         file_pb_kmgm_proto_enumTypes,
		MessageInfos:      file_pb_kmgm_proto_msgTypes,
	}.Build()
	File_pb_kmgm_proto = out.File
	file_pb_kmgm_proto_goTypes = nil
	file_pb_kmgm_proto_depIdxs = nil
}
